DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "ROSSO"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "GIGI"

DEF RIVALNAME1 EQUS "BLU"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "PIPPO"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "BLU"
DEF PLAYERNAME2 EQUS "GARY"
DEF PLAYERNAME3 EQUS "PIPPO"

DEF RIVALNAME1 EQUS "ROSSO"
DEF RIVALNAME2 EQUS "ASH"
DEF RIVALNAME3 EQUS "GIGI"
ENDC
